### ISSUE TITLE
侧边栏导航线上和预览不符合

### ISSUE THREAD

**Issue by erdun** [cloudnativeto/cloudnative.to#104]
### 预览
https://deploy-preview-103--cloudnativeto.netlify.app/blog/flame-graph/
![image](https://user-images.githubusercontent.com/16429864/86425340-73a03c80-bd17-11ea-9b90-897c3a66798d.png)
![image](https://user-images.githubusercontent.com/16429864/86425496-eb6e6700-bd17-11ea-874b-767549ad08f6.png)

### 线上
https://cloudnative.to/blog/flame-graph/
![image](https://user-images.githubusercontent.com/16429864/86425352-7ef36800-bd17-11ea-9744-c2a8e7fa40b4.png)
![image](https://user-images.githubusercontent.com/16429864/86425504-f2957500-bd17-11ea-8de0-250487b040da.png)

TableOfContents 编译出来的不一样,是不是预览编译镜像和部署的镜像版本不一致导致

@rootsongjc

**Comment by rootsongjc** [comment]
看样子是多了 href 格式不一样，我查看下 netlify 预览配置的 hugo 版本与我们的 github action 是否一致。

**Comment by rootsongjc** [comment]
![image](https://user-images.githubusercontent.com/3328185/86429000-c7fbea00-bd20-11ea-904f-4c1159e70ef8.png)
![image](https://user-images.githubusercontent.com/3328185/86429020-d4804280-bd20-11ea-9d74-2fc4a85e1bd4.png)

两者的 Hugo 版本是一致的。

**Comment by rootsongjc** [comment]
该问题不影响阅读体验，先设置为 stale，以后有空再修。

**Comment by rootsongjc** [comment]
本站使用 GitHub Action 发布，将 Hugo 版本更新至 0.65.3 后该问题已解决。
![image](https://user-images.githubusercontent.com/3328185/89763774-c72b5480-db25-11ea-9df9-93446b2018a0.png)
