### ISSUE TITLE
[博客] Kubernetes 编程基础

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#109]
新增一篇博客，来自 @gasxia https://jinrunsen.com/kubernete-programming-base/
文章还需要整理和优化下，提交到社区官网。
同时可以分享下这个资料：https://github.com/cloudnativeto/community/issues/37

**Comment by gasxia** [comment]
已整理优化，麻烦再审一下。

**Comment by rootsongjc** [comment]
在提交 PR 前的几点建议：
1. 所有引用的别人的图片需要注明出处
2. 文章开头写一段摘要，介绍这篇文章究竟是要讲什么，目前的那段太长了。

**Comment by rootsongjc** [comment]
@GuangmingLuo 会跟进本文的 review 和发布。

**Comment by GuangmingLuo** [comment]
@gasxia 请根据 rootsongjc 提的意见完成文章优化，然后直接提交PR。后续review直接基于PR即可。

**Comment by rootsongjc** [comment]
已发布，关闭 issue。
