### ISSUE TITLE
Kubernetes源码研习社优秀笔记，可以联系作者，在整理后投稿到社区

### ISSUE THREAD

**Issue by gasxia** [cloudnativeto/cloudnative.to#121]
主题：Informer源码阅读

1. @sundongmin 从初始化调用链和数据流向的角度分析了informer各个组件，画了很多图<https://juejin.im/post/6860480938699472909/>

2. @linxuyalun 内容丰富，informer源码细节写的很清楚 https://linxuyalun.github.io/2020/08/10/k8s-client-go/

3. @janeliul 从为什么要这么设计实现的角度写了笔记，很有价值 https://github.com/JaneLiuL/study-client-go/blob/master/Informer-study.md

4. @strive-after 对重要组件都写了篇文章细致分析 https://blog.csdn.net/weixin_45413603/article/details/107995986

**Comment by rootsongjc** [comment]
笔记内容可以整理到 https://i.cloudnative.to/kuberentes/ 里，不用提交到官网博客上。
