### ISSUE TITLE
[翻译] Migrating to Service Mesh

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#174]
原文链接：https://allegro.tech/2020/05/migrating-to-service-mesh.html
发布时间：2020-05-07
作者：Dariusz Jędrzejczyk

**Comment by addozhang** [comment]
我这个我来翻译吧，麻烦 assign 给我 🙏。

**Comment by rootsongjc** [comment]
已分配给 @addozhang ，翻译完成后请直接向本仓库提交 PR。

**Comment by rootsongjc** [comment]
已发布，见：https://cloudnative.to/blog/migrating-to-service-mesh/
