### ISSUE TITLE
[网站] 城市站页面优化

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#184]
![image](https://user-images.githubusercontent.com/3328185/95581220-34e2f680-0a6b-11eb-8b63-beb1a2549b88.png)

城市站页面[第一版](https://github.com/cloudnativeto/cloudnative.to/pull/173)，已经完成，感谢 @luoyan35714

不过还有很多需要优化的点，比如上图中，感觉太紧凑了，中间需要隔点空间。

大家可以浏览下，提提意见，https://cloudnative.to/city/

**Comment by lhb008** [comment]
<img width="1440" alt="Screen Shot 2020-10-09 at 8 26 25 PM" src="https://user-images.githubusercontent.com/42570491/95582801-ba67a600-0a6d-11eb-9ec8-790e7cccf0d1.png">

这个背景图感觉可以设置成城市logo墙，现在每个城市都开始设计logo了。

**Comment by lhb008** [comment]
点击详情按钮后，跳转至城市站自己的网页。不用再跳转至github issue页面。加入流程之类的可以放在页面上。

**Comment by rootsongjc** [comment]
我觉得左侧就显示被点选的城市站页面显得太单薄，默认可以显示所有城市站，当在地图上点击某个城市的图钉后，左侧过滤出该城市，就像盖度地图默认的搜索结果展示那样，如下图：
![image](https://user-images.githubusercontent.com/3328185/95583193-5a253400-0a6e-11eb-8f76-c428d56119d6.png)

**Comment by rootsongjc** [comment]
> 点击详情按钮后，跳转至城市站自己的网页。不用再跳转至github issue页面。加入流程之类的可以放在页面上。

这块就是第二期要做的，需要给城市站做个独立的页面，每个城市都有一个 `https://cloudnative.to/city/xxx` 的页面，该页面可以放城市站介绍。

**Comment by rootsongjc** [comment]
> <img alt="Screen Shot 2020-10-09 at 8 26 25 PM" width="1440" src="https://user-images.githubusercontent.com/42570491/95582801-ba67a600-0a6d-11eb-9ec8-790e7cccf0d1.png">
> 
> 这个背景图感觉可以设置成城市logo墙，现在每个城市都开始设计logo了。

这个创意很好，不过考虑到移动端的体验（分辨率会跟 PC 不一样，需要单独再搞一个图片），最好还是放一个虚拟背景。

**Comment by rootsongjc** [comment]
![image](https://user-images.githubusercontent.com/3328185/95594889-15a19480-0a7e-11eb-998b-70126ee63395.png)
参考这张图片 @luoyan35714

**Comment by rootsongjc** [comment]
城市站页面上再加个概述专栏，放在地图下面吧。说明目前有多少个城市站还有城市站的运作规则。

**Comment by rootsongjc** [comment]
城市站页面经过本次更新，布局已经没有问题了。

![image](https://user-images.githubusercontent.com/3328185/96343059-60e62380-10cc-11eb-8061-429349016178.png)

不过点击右侧地图中每个城市，左面的列表里并没有过滤出对应的城市来，这里需要加一个响应式的动作。让点击地图跟左面的列表产生关联。 @luoyan35714

**Comment by rootsongjc** [comment]
移动端适配也有些问题，如下图。
![IMG_7749](https://user-images.githubusercontent.com/3328185/96720809-d2c8b080-13dd-11eb-8eff-315b75523206.PNG)

**Comment by rootsongjc** [comment]
城市站的页面已经改版完成，感谢 @luoyan35714 关闭 issue。
