### ISSUE TITLE
[翻译] Request Affinity with Istio

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#185]
原文：https://cashapp.github.io/2020-08-04/request-affinity-with-istio
作者：CashApp
发布时间：2020 年 8 月 4 日

**Comment by NickSu86** [comment]
认领

**Comment by rootsongjc** [comment]
已分配给 @NickSu86 ，请在三个工作日内提交 PR。

**Comment by rootsongjc** [comment]
已发布，关闭 issue，见https://cloudnative.to/blog/request-affinity-with-istio/
