### ISSUE TITLE
能否能给开发中的项目一点声音和展示: LaashubSOA, 以及添加关注实际工作(走进一线运维人员的心里)

### ISSUE THREAD

**Issue by tristan-tsl** [cloudnativeto/cloudnative.to#208]
云原生社区有展示开发中的项目的想法吗?

**Comment by tristan-tsl** [comment]
项目地址: https://github.com/laashub-soa/laas-soa, 项目的demo版本的地址: https://github.com/laashub-soa/laasops-DEPRECATED, 查看已经开发的功能: https://github.com/laashub-soa/laasops-DEPRECATED/blob/master/docs/current_progress/2020-04-12_14-04/

**Comment by tristan-tsl** [comment]
孵化的项目都在apache本身，云原生社区是一个分享和交流的地方，不是做技术孵化的
但是我又加入不了apache项目孵化, 暂时对我有点要求太高了
在云原生社区的一个好处就是本土化、标准低一点
关于项目的交流我觉得也是挺重要的吧, 发现项目->关注项目->使用项目, 一直以来不都是在写技术相关使用的文档

**Comment by tristan-tsl** [comment]
docker没有正式出来之前我们都在关注ansible、linux、centos这样的项目, 但是docker release之后我们又开始关注docker了, 能否提前发现docker呢?
kubernetes没有正式出来之前我们都在关注docker compose、docker swarm这样的项目, 但是kubernetes release之后我们又开始关注kubernetes了, 能否提前发现kubernetes呢?
通过提前关注可以稍微调整一个docker和kubernetes自身的发展, 形成一个良性的循环, 降低项目难度

**Comment by tristan-tsl** [comment]
我用过太多项目都没有声音, 如果能给他们一个声音, 而这样声音又确实是一线运维人员确实需要的, 是否也是正确的呢
除了盯着高大上的技术其实还需要很多能够帮助一线运维人员的项目
在博客右边其实可以加一个项目项, 其实项目项和博客很类似, 但是更加注重于实际工作

**Comment by tristan-tsl** [comment]
我目前有1年多非常充实的一线运维经验、独立负责过两家公司的运维, 易佰网络和聚里优享, 用了非常多的项目

**Comment by rootsongjc** [comment]
云原生社区主要专注于云原生领域的开源项目，如果你的项目与云原生领域有关且具有社会价值，社区可以帮助你孵化和推广。

**Comment by tristan-tsl** [comment]
这个项目后面可以架构在kubernetes之上，作为dashboard使用，打通监控

**Comment by tristan-tsl** [comment]
不需要推广，只需要展示即可

**Comment by tristan-tsl** [comment]
从抽象的角度来看就是在做技术下沉度

**Comment by rootsongjc** [comment]
你可以先一篇博客介绍你的项目及其与云原生的关系。

**Comment by tristan-tsl** [comment]
我可以以kubernetes运维平台为例子写一篇文章

**Comment by tristan-tsl** [comment]
https://github.com/laashub-soa/laas-soa/blob/master/docs/%E6%8A%95%E7%A8%BF%E5%88%B0%E5%85%B6%E4%BB%96%E5%B9%B3%E5%8F%B0/%E4%BA%91%E5%8E%9F%E7%94%9F%E7%A4%BE%E5%8C%BA/%E7%8E%B0%E4%BB%A3%E5%8C%96%E8%BF%90%E7%BB%B4%E5%B9%B3%E5%8F%B0%E5%BB%BA%E8%AE%BE%E7%9A%84%E8%89%BA%E6%9C%AF%E4%B8%8E%E5%8A%A1%E5%AE%9E.md

**Comment by tristan-tsl** [comment]
> 你可以先一篇博客介绍你的项目及其与云原生的关系。

https://github.com/laashub-soa/laas-soa/blob/master/docs/%E6%8A%95%E7%A8%BF%E5%88%B0%E5%85%B6%E4%BB%96%E5%B9%B3%E5%8F%B0/%E4%BA%91%E5%8E%9F%E7%94%9F%E7%A4%BE%E5%8C%BA/%E7%8E%B0%E4%BB%A3%E5%8C%96%E8%BF%90%E7%BB%B4%E5%B9%B3%E5%8F%B0%E5%BB%BA%E8%AE%BE%E7%9A%84%E8%89%BA%E6%9C%AF%E4%B8%8E%E5%8A%A1%E5%AE%9E.md

**Comment by rootsongjc** [comment]
已经一个多月了，无博客提交，关闭 issue。

**Comment by tristan-tsl** [comment]
已经在开发阶段了，后续release之后再来写
