### ISSUE TITLE
[招聘]redhat 云原生PaaS平台解决方案架构师

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/cloudnative.to#238]
需要来个人帮忙提交下pr，我没时间搞

## 招聘信息如下：

岗位：
高级原厂咨询服务顾问 - OpenShift
岗位介绍：
红帽专业咨询服务团队正在招募两名PaaS高级顾问加入我们。这个岗位将要负责配合售前团队在售前阶段进行技术选型以及方案制定，并将红帽PaaS解决方案（含OpenShift）在客户现场实施落地，并且帮助客户解决技术问题，进行故障排除。根据您通过了解客户的基础架构和业务需求，提出解决痛点的可行性建议，并帮助他们制定IT战略决策，同时将在客户端推广和分享红帽的解决方案。
岗位要求：
熟练掌握Docker和Kubernetes技术技能
在J2EE解决方案的设计，开发和实施方面具备丰富的经验
了解JBoss, WebLogic, WebSphere, WebMethods, Tibco等中间件解决方案知识和经验
具有Agile Coach的知识和经验者优先
具有微服务架构师经验优先
具有DevOps经验优先
具有应用开发经验优先
能够接受国内各地出差
工作地点：
广州 or 深圳
对英语的要求：
能够进行读写
投递简历
请将中文或英文简历发送至：lshi@redhat.com或联系Jimmy Shi(13241214861)了解详情
Red Hat公司介绍
红帽是全球领先的企业开源软件解决方案提供商，才用社区支持的方法来提供可靠和高性能的Linux，混合云，容器和Kubernetes技术。红帽可以帮助客户集成新的和现有的IT应用程序，开发云原生应用程序，在我们行业领先的操作系统上进行标准化以及自动化，保护和管理复杂的环境。

**Comment by rootsongjc** [comment]
发布了：https://cloudnative.to/job/redhat/
关闭 issue。
