### ISSUE TITLE
[招聘]redhat 云原生 PaaS 高级顾问

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/cloudnative.to#258]
需要来个人帮忙提交下pr，我没时间搞

### 岗位：
云原生 PaaS 高级顾问

### 岗位介绍：
红帽专业咨询服务团队正在招募两名 PaaS 高级顾问加入我们。这个岗位将要负责配合售前团队在售前阶段进行技术选型以及方案制定，并将红帽 PaaS 解决方案（含 OpenShift）在客户现场实施落地，并且帮助客户解决技术问题，进行故障排除。根据您通过了解客户的基础架构和业务需求，提出解决痛点的可行性建议，并帮助他们制定 IT 战略决策，同时将在客户端推广和分享红帽的解决方案。

### 岗位要求：
• 熟练掌握 Docker 和 Kubernetes 技术技能
• 具备良好的Linux运维和网络技能
• 在 J2EE 解决方案的设计，开发和实施方面具备丰富的经验优先考虑
• 具有微服务架构师经验优先
• Base上海，华东地区出差，出差少

### 工作地点：
上海

### 投递简历

请将中文或英文简历发送至：mwan@redhat.com 或联系 Minty Wang (18310229613) 了解详情。

### Red Hat公司介绍
红帽是全球领先的企业开源软件解决方案提供商，才用社区支持的方法来提供可靠和高性能的Linux，混合云，容器和Kubernetes技术。红帽可以帮助客户集成新的和现有的IT应用程序，开发云原生应用程序，在我们行业领先的操作系统上进行标准化以及自动化，保护和管理复杂的环境。

**Comment by Miss-you** [comment]
issue
https://github.com/cloudnativeto/cloudnative.to/issues/258
参考：
https://github.com/cloudnativeto/cloudnative.to/blob/master/content/zh/job/redhat.md

**Comment by rootsongjc** [comment]
所有岗位都以公司为单位来发布吧，合并到 Redhat 已经发布的岗位页面里。

**Comment by Miss-you** [comment]
好的
