### ISSUE TITLE
[翻译] Helm Chart Repository Deprecation Update

### ISSUE THREAD

**Issue by majinghe** [cloudnativeto/cloudnative.to#264]
Helm chart 仓库地址变更及旧仓库地址弃用信息。

https://www.cncf.io/blog/2020/11/05/helm-chart-repository-deprecation-update/

**Comment by majinghe** [comment]
@rootsongjc  提交了一个翻译issue。关于helm 仓库更换地址的blog。这个最近正好遇到了，就打算翻译出来。我自己认领了。

**Comment by rootsongjc** [comment]
本文已合并并发布，见https://cloudnative.to/blog/helm-chart-repository-deprecation-update/ 关闭 issue。
