### ISSUE TITLE
[官网] 优化博客图片上的标签显示

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#277]
![image](https://user-images.githubusercontent.com/3328185/99536941-fafbfd00-29e5-11eb-8792-233505c29d71.png)

现在的博客 banner 图片上标签只能展示功能，希望可以加上链接，作为标签过滤功能，比如点击 `helm` 可以跳转到 https://cloudnative.to/tags/helm/

**Comment by pefish** [comment]
category和tag是多对多的关系，如何根据category跳转到tag页面

**Comment by pefish** [comment]
是不是选择第一个tag就好了

**Comment by rootsongjc** [comment]
其实这个标签显示的 categories 里面的配置，但是目前我们把 categories 页面给禁用了，大部分的 categories 配置与tags 配置里的一个是一样的，但是不确定是否存在不一样的情况。可以先去 tag 的第一个作为链接。

**Comment by pefish** [comment]
> 其实这个标签显示的 categories 里面的配置，但是目前我们把 categories 页面给禁用了，大部分的 categories 配置与tags 配置里的一个是一样的，但是不确定是否存在不一样的情况。可以先去 tag 的第一个作为链接。

有些tag页面是404

**Comment by rootsongjc** [comment]
只要会博客中有配置过的 tag，不应该会有 404。可以举个例子吗？那篇博客里有 404 错误的 tag？

**Comment by pefish** [comment]
> 只要会博客中有配置过的 tag，不应该会有 404。可以举个例子吗？那篇博客里有 404 错误的 tag？

文章<零信任网络安全：“从不信任，永远验证”>中有tag “zero trust cybersecurity”

但是打开 https://cloudnative.to/tags/zero%20trust%20cybersecurity/  是404页面

这是一个例子，还有很多其他的tag404

**Comment by rootsongjc** [comment]
这个链接应该是：https://cloudnative.to/tags/zero-trust-cybersecurity
空格被用连字符替换了

**Comment by rootsongjc** [comment]
已完成，关闭 issue。
