### ISSUE TITLE
[翻译] Running database migrations when deploying to Kubernetes

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#409]
地址：https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/

**Comment by nicksu-kdkd** [comment]
认领

**Comment by rootsongjc** [comment]
Done, read the translations https://cloudnative.to/blog/running-database-migration-when-deploying-to-kubernetes/
