### ISSUE TITLE
请删除一下招聘帖子

### ISSUE THREAD

**Issue by qiankunli** [cloudnativeto/cloudnative.to#497]
https://github.com/cloudnativeto/cloudnative.to/blob/fd6f5c43278ddfa78f5013e2fa9de2838b0ae8b4/content/zh/job/ximalaya-k8s.md
https://github.com/scany1211/awesome/blob/478e88212af8b5aa6d9cb927dcefde7e96c3773c/_posts/Employee/2021-03-23-java.md
麻烦删除一下哈， 我们现在不招人了。

**Comment by rootsongjc** [comment]
所有招聘链接都已下线。
