### ISSUE TITLE
云原生志愿者计划 - 网站改版

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#66]
2020 年 6 月 13 日晚，云原生社区进行了志愿者计划 kickoff，其中网站小组，包括 @erdun @flutterwang @jianghongb @baijunyao，因为该网站之前是我开发的，对这个网站的架构比较了解，在此先给大家介绍下网站架构及需求。

## 云原生社区网站架构

云原生社区官网主要用于展示社区的基本信息（创始团队、投稿、博客等），以下是网站的基本情况：

- 纯静态网站
- 网站源码存储在 https://github.com/cloudnativeto/cloudnative.to
- 网站构建后的代码在 https://github.com/cloudnativeto/cloudnativeto.github.io
- 使用 [Hugo](https://gohugo.io) 构建
- 使用 GitHub Pages 托管，无设置后端服务器
- 使用 GitHub Action 自动发布
- 支持多语言

## 模块

根据主题风格的不同，当前网站主要包含以下模块：

- 主页
- 团队
- 关于、联系、投稿指南
- 博客（主要模块）

## 需求

网站需求主要包含改进需求和新增需求。

### 改进需求：博客

博客是网站的主要内容，可以有以下改进点：

- 每篇文章中增加目录导航（TOC），最好放在文章右侧，可隐藏
- 每篇文章中增加相关文章推荐，可以使用 Hugo 的推荐模块
- 图片增加个放大功能，有的图片看上去太小了
- 博客的内容模板，增加一个作者信息展示，参考：https://thenewstack.io/container-sprawl-is-the-new-vm-sprawl/

### 新增需求：嘉宾页面

云原生社区邀请了众多大咖嘉宾，这些嘉宾都在知识星球里，而外界对此无所知，需要在社区网站上展示下，做一个单独的页面。
展示社区嘉宾的信息。

### 新增需求：站内搜索

随着社区内容越来越多，需要增加一个站内搜索功能，帮助大家迅速找到需要的信息。

**Comment by baijunyao** [comment]
站内搜索可以尝试的方案： https://docsearch.algolia.com

**Comment by erdun** [comment]
内容页不确定具体要展示那些东西，怎样的展示形式，所以没有弄

**Comment by rootsongjc** [comment]
内容页先等等，可以先把其他的功能完成，内容我们这个周的社区会议上讨论下吧。一起讨论个 proposal，需要准备哪些资料，已有的从知识星球里获得，需要补充的，比如嘉宾的照片可以再跟嘉宾要。

**Comment by rootsongjc** [comment]
改版已完成
