### ISSUE TITLE
[featrue] 增加目录导航

### ISSUE THREAD

**Issue by erdun** [cloudnativeto/cloudnative.to#72]
每篇文章中增加目录导航（TOC），最好放在文章右侧，可隐藏

refer #66

**Comment by erdun** [comment]
现在右边已经有 `最新文章`, `类别`, `标签`， 之后还要增加 `作者介绍`, `目录导航`， 整个右边是否过长

**Comment by rootsongjc** [comment]
可以采用以下几种形式来解决：
1. 一个悬浮可折叠的 TOC，只有鼠标点击或者 hover 的时候才显示，类似与 [Gitbook](https://www.servicemesher.com/istio-handbook/) 的形式
2. 当读者浏览的页面下滑的时候自动隐藏右侧原来的内容，只显示 TOC

**Comment by rootsongjc** [comment]
完成，关闭该 issue。感谢 @erdun
