### ISSUE TITLE
[featrue] 新增嘉宾页面

### ISSUE THREAD

**Issue by erdun** [cloudnativeto/cloudnative.to#76]
云原生社区邀请了众多大咖嘉宾，这些嘉宾都在知识星球里，而外界对此无所知，需要在社区网站上展示下，做一个单独的页面。
展示社区嘉宾的信息。

refer #66

**Comment by rootsongjc** [comment]
取消嘉宾页面，使用https://github.com/cloudnativeto/cloudnative.to/issues/272 替代。关闭issue。
