### ISSUE TITLE
[featrue] 新增站内搜索

### ISSUE THREAD

**Issue by erdun** [cloudnativeto/cloudnative.to#77]
随着社区内容越来越多，需要增加一个站内搜索功能，帮助大家迅速找到需要的信息。

refer #66

**Comment by baijunyao** [comment]
https://docsearch.algolia.com 提交申请后几天了还没收到邮件回复，可能需要选择其他方案，我研究研究。

**Comment by baijunyao** [comment]
我用我的纯文档性质的网站和咱的网站向 [DocSearch](https://docsearch.algolia.com) 提交了申请测试；但是都没有收到邮件回复；原因不明； 
因此我现在尝试的方案是自己使用 [docsearch-scraper](https://github.com/algolia/docsearch-scraper) 抓取数据并推送到 Algolia ； 

这里涉及到 3 个问题； 

1. 现在是使用我的个人邮箱创建的 Algolia ； 需要考虑是否使用咱官方的邮箱创建 Algolia 账号； 
2. 现在是在我个人的服务器设置的定时任务每天凌晨爬取官网数据一次； 需要考虑是否在官方的服务器上运行爬取数据的程序；
3. 现在爬取数据的频率是否满足需求； 如果希望能更及时的搜索到新增的文章； 可以考虑通过 GitHub 的 Hook ； 在每次 merge 代码后都执行爬取数据的程序；

**Comment by rootsongjc** [comment]
1. 社区官方邮箱，我们使用 contact@cloudnative.to，请联系 @GuangmingLuo 
2. 目前我们社区还没有官方的服务器，因为社区并没有购买服务器，不过我可以在我的树莓派上部署一个
3. 目前每天爬取一次的频率已经足够，可以直接使用 GitHub action，在 merge 的时候自动更新数据

**Comment by baijunyao** [comment]
## 创建账号
1. 注册 [Algolia](https://www.algolia.com/)  

2. 创建 application  
![image](https://user-images.githubusercontent.com/9360694/85948189-03459400-b982-11ea-8188-62686554e529.png)

3. 创建 index  
![image](https://user-images.githubusercontent.com/9360694/85948231-46a00280-b982-11ea-8269-a0e8feac3b8c.png)

4. 创建 key
![image](https://user-images.githubusercontent.com/9360694/85948288-ae564d80-b982-11ea-931d-abd079842cae.png)    
- 不要选择 Indices
- ACL 选中 `addObject`、 `editSettings`、 `deleteIndex`  
![image](https://user-images.githubusercontent.com/9360694/85948351-068d4f80-b983-11ea-9726-8609dfdcf804.png)  
创建完成后可以查看到 ACLs 为  `addObject`、 `editSettings`、 `deleteIndex` 的 key 1 和  ACLs 为 `search` 的 key2  
![image](https://user-images.githubusercontent.com/9360694/85948654-a13a5e00-b984-11ea-84bb-bc1f993b0526.png)  
在 Your API Keys 页面得到 Application ID
![image](https://user-images.githubusercontent.com/9360694/85948723-f24a5200-b984-11ea-958c-4b78f9b5f6e6.png)  
- 把 Application ID 和 key1 给 @rootsongjc 
- 把 Application ID 和 key2 给我 @baijunyao 

## 爬取数据的命令
```bash
docker run --env APPLICATION_ID=xxx --env API_KEY=xxx --env CONFIG='{"index_name":"DocSearch","start_urls":["http://cloudnative.to/"],"selectors":{"lvl0":{"selector":".bg-cover h2","default_value":"Blog"},"lvl1":".content h1","lvl2":".content h2","lvl3":".content h3","lvl4":".content h4","lvl5":".content h5","text":".content p"},"selectors_exclude":["nav","footer",".aside"],"min_indexed_level":1,"scrap_start_urls":false}' algolia/docsearch-scraper
```
使用 创建账号 步骤中的 Application ID 和 key1 替换上面命令中的 `APPLICATION_ID` 和 `API_KEY` 的 xxx ;

##  GitHub Action
我在开发的时候第一个想到的认为最合适的也是使用 GitHub Action 在 merge 的时候更新 Algolia 索引； 但是有两个原因致使我放弃了；  
1. 可能违反 GitHub Action 允许的使用范围； 可能违规；
2. 我在我 fork 的项目上测试过 [GitHub Action](https://github.com/baijunyao/cloudnative.to/runs/809772237?check_suite_focus=true) 似乎在 Algolia 的域名在 GitHub Action 被禁止了； 
![image](https://user-images.githubusercontent.com/9360694/85949083-38a0b080-b987-11ea-880d-4b5dbbd5600f.png)

**Comment by rootsongjc** [comment]
已完成了 algolia 的配置，使用是我的账号。
![image](https://user-images.githubusercontent.com/3328185/86033318-5b0bfa00-ba6b-11ea-8170-72332d653e5b.png)

**Comment by rootsongjc** [comment]
移动端适配还得改下。@erdun

**Comment by rootsongjc** [comment]
现在样式都已经调整完毕，只剩下一个问题：如何触发更新，需要确认下 Github Actions 是否可行。

**Comment by baijunyao** [comment]
没有在 Github Actions 上调试成功；

**Comment by rootsongjc** [comment]
我在 DigitalOcean 上买了一台 1C2G 的服务器，我想可以用它来搞了，不一定要用 GitHub Action，写个 webhook 即可。

**Comment by erdun** [comment]
爬虫会有入口页，然后找这个页面的链接遍历，控制入口页面，过滤链接应该可以只爬博客的

**Comment by rootsongjc** [comment]
是每次执行 docker 那个命令就会遍历整个网站，我的 algolia 账号的免费操作额度已经用完了。

**Comment by erdun** [comment]
我申请一个看看

**Comment by baijunyao** [comment]
什么超了？ 我之前申请的账号； 每天爬一次数据； 在我服务器上运行着没取消； 现在还没超额呢；  可以限定抓取范围；

**Comment by rootsongjc** [comment]
我的博客的那个应用已经超额了，被限制了，超过了操作次数，因为我每次有新的 PR 或者推送到 master 分支就会触发一次全量更新。

**Comment by erdun** [comment]
我看文档好像可以直接后台上传数据，不通过爬虫爬取

**Comment by baijunyao** [comment]
> 是每次执行 docker 那个命令就会遍历整个网站，我的 algolia 账号的免费操作额度已经用完了。

看来这个触发机制不是很合理了； 不能每次 push 就更新索引； 很多时候 push 都是更新样式之类的；

**Comment by baijunyao** [comment]
> 我看文档好像可以直接后台上传数据，不通过爬虫爬取

那样的话； 就需要写代码上传数据了；   
手动在后台上传数据不合适；

**Comment by rootsongjc** [comment]
是的，我曾经用过一个 [Python 脚本](https://github.com/rootsongjc/rootsongjc-hugo/blob/5c1e6689cb2c4387897bf9a331d570051c1bf1e5/scripts/hugo_algolia.py)用来更新 algolia 的 index，可以参考下。

**Comment by rootsongjc** [comment]
已完成，使用内建搜索。
