### ISSUE TITLE
官网访问很慢很慢哟(经常)

### ISSUE THREAD

**Issue by shenhonglei** [cloudnativeto/cloudnative.to#80]
https://cloudnative.to 有时加了V&P(N,访问起来，还是很慢，若能想想办法提升下访问速度，用户体验会更加完美，谢谢

**Comment by zeusro** [comment]
![image](https://user-images.githubusercontent.com/5803609/85080489-e4b20100-b1fb-11ea-8e50-102c1be373d7.png)
https://cloudnative.to 
用的是`cloudflare`解析

**Comment by rootsongjc** [comment]
网站使用的是 cloudflare 做 CDN，托管在GitHub Pages 上，因为域名后缀的原因无法在国内备案，有推荐的部署方式吗？

**Comment by rootsongjc** [comment]
@yekangming 将负责网站的架构调整和速度优化。

**Comment by rootsongjc** [comment]
目前使用 GItHub pages 的免费方案，使用Cloudflare作为 CDN，速度还可以接受。
