### ISSUE TITLE
[feature] 修改 sidebar 和 footer 的样式

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#82]
现在博客页面 sidebar 中包含的内容太多 @erdun ：
- 最新文章（三篇）
- category
- tag
- 作者头像和介绍
- 目录

这样将导致 sidebar 太长，需要精简或者优化下，方案如下：

- 将目录放在 sidebar 最上面
- category 和 tag 修改下展示形式，使用词云的形式（或者有更好的形式，不要那么占版面的）
- 最新文章移动到 footer 里

**Comment by erdun** [comment]
1. 最新文章放到下面, 后续换成 文章推荐
2. 目录使用 sticky 方式的适合放在最下面
3. category 和 tag 字体太大，占用空间过多，可以使用词云

**Comment by rootsongjc** [comment]
![image](https://user-images.githubusercontent.com/3328185/85996961-7a8b2e80-ba3b-11ea-9270-c7fbf5d0941a.png)

建议把这个最新文章的模块去掉，放到页面的 footer 里，直接放链接即可。

类似[这样的](https://jimmysong.io/about/)，再加上合作社区或者合作伙伴的链接栏。

![image](https://user-images.githubusercontent.com/3328185/85997061-9f7fa180-ba3b-11ea-946f-c168fce24f0a.png)
