### ISSUE TITLE
提交招聘信息

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/cloudnative.to#87]
## 如何提交招聘信息

因为社区了很多人需要发布招聘需求及找工作，因此需要在官网上单独设置一个招聘页面（Job Board）。

1. 如何提交招聘信息请先联系 [Jimmy](https://jimmysong.io/about) 并参考[这个 PR](https://github.com/cloudnativeto/cloudnative.to/pull/122)，仅接受与云原生相关的职位推广。
2. 填写[招聘人员信息登记表](https://wj.qq.com/s2/8820067/ce4a/)

完成以上步骤后，就可以在社区的微信群中发布云原生官网上的职位链接，社区也会将职位发布到公众号上。

**Comment by rootsongjc** [comment]
最近招聘需求越来越多了，我们要考虑做一个 Job board 了。

**Comment by rootsongjc** [comment]
页面的需求：类似于 <https://jimmysong.io/job>的页面，使用 list 展示所有招聘需求，点击每个招聘进到详情页面 @baijunyao

**Comment by rootsongjc** [comment]
https://github.com/cloudnativeto/cloudnative.to/pull/110 第一期完成，第二期需要将招聘信息格式化 @baijunyao 
我觉得可以在 Markdown 的 header 里加一些配置，比如：

- 公司
- 部门
- 岗位
- base 地
- 类型（实习生、社招）
- 部门

确定固定格式，要求所有提交招聘需求的人都要按照该格式填写。

**Comment by baijunyao** [comment]
hogo 我不熟悉哈； 是自带这样的功能？ 还是需要开发扩展？

**Comment by rootsongjc** [comment]
不需要开发扩展，只需要确定好 Markdown 文档头部的 YAML 头格式配置即可，在 layout 中可以使用 Go template 获取 Markdown 中的的 YAML 配置。

**Comment by charles-liming** [comment]
金山办公北京 小米产业园 招聘K8S运维工程师
Position Requirements
熟悉kubernetes、docker，熟练掌握k8s核心组件的架构及原理，有项目架构和实施经验者优先；
掌握golang语法，具备Go语言项目代码的阅读能力和基于golang对k8s的二次开发能力；
熟练掌握Linux的操作，具备shell/python的编程能力；
熟练基础组件（Nginx、Redis、MQ）的使用、调优和问题处理；
了解云原生相关技术，如服务网格，serverless等；
具备针对复杂问题的分析能力和针对新技术深入研究探索的能力；
具备深入挖掘客户需求，探索用户场景，并规划建设实施方案的能力；
具备良好的团队沟通协作能力和工作执行力。

**Comment by rootsongjc** [comment]
@charles-liming 请提交 PR，不要在本 issue 中回复。

**Comment by runzexia** [comment]
@rootsongjc  请教一下，JD可以是英文的吗

**Comment by rootsongjc** [comment]
尽量提供双语版，官网有英文和中文页面，中文页面的话就发中文JD。

**Comment by Vivian7755** [comment]
京东招聘产品经理 
Base: 北京
岗位职责：
负责京东移动技术开发平台mPaaS的产品规划与设计，打造京东移动开发 DevOps End to End Solution
负责京东小程序平台产品规划与设计，打造京东小程序生态
与业务对接需求，对需求进行分析，管控，细化，以及指定产品版本计划，设计产品原型，与项目经理，交互/视觉设计师，开发测试紧密配合，确保项目按时，高质量上线
定期对竞品进行分析，吸纳先进思想，寻找差异，结合我们实际情况制定适合我们的产品策略与规
研发配合，定期对用户进行调研，寻找痛点，不断完善产品，提升产品的用户体验
与业务团队的良好沟通和对市场的深入研究，深入理解和发现业务问题，抽象总结，形成产品解决方案；同时推动技术产品化对外输出

任职要求：
1. 计算机及其相关专业本科以上学历，2年产品经验，具有移动开发，前端开发，以及移动端产品经验
2. 熟悉相关移动端包含ios， Android ，小程序，H5等相关技术背景，有过平台类产品经验
3. 了解移动开发环境与Devops工程与流程，对于开发平台类产品与相关系统等产品有清晰的认知，能够深入分析公司业务，用户，合作伙伴的痛点
4. 逻辑思维能力强，能够对问题进行结构性的分析，有整体的认知，并且能迅速找到切入点，并能给出自己的解决方案
5. 具备较强的需求分析，产品规划，项目推动能力，熟悉产品开发的全流程
6. 能够熟练使用各种工具（Axure， Xmind，Visio，PPT，Excel）描述业务设计原型，业务需求，及撰写方案，有良好的文案功底
7. 对前端JavaScrip技术，Android，IOS等客户端技术有一定的了解优先，有研发背景优先
8. 有优秀的团队沟通与协调能力，团队合作精神

**Comment by muercy** [comment]
公司: VMware
部门: PSO
岗位: Senior Consultant
base 地: 北京/上海
类型: 社招
JD:
1，熟悉docker或containerd，Kubernetes，镜像仓库，常见的CNI（flannel，antrea，calico等），有应用容器化经验；

2，熟悉微服务架构，了解Spring cloud或Dubbox的开发经验；

3，了解一个或多个常用中间件redis，kafka，rabbitmq等；

4，了解ITSM，运维管理规范等；

5，了解开发规范，测试案例管理等；

6，了解敏捷，Devops及数字化对企业转型的意义

7.   较强的学习能力

加分项，熟悉虚拟化，或者熟悉网络及SDN，有架构师或技术经理经历

**Comment by rootsongjc** [comment]
@muercy @Vivian7755 请提交 PR，不是提到这个 issue 里。

**Comment by rootsongjc** [comment]
新模版中去掉了招聘页面，不再官网上维护招聘信息。
