### ISSUE TITLE
[投稿转载]漏洞科普——fastjson远程命令执行漏洞原理

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/cloudnative.to#88]
文章简介：

为什么fastjson有这么多安全漏洞？

大家都知道，fastjson 漏洞产生的原因在于反序列化时可能被利用而造成命令执行。

个人觉得fastjson 有如此多的安全漏洞的根本原因在于它的设计初衷是允许对任意类型进行反序列化，本质上不是一种安全的设计模式，因为当对某种类型进行反序列化可能触发命令执行时，组件设计者此时只能选择将其加入反序列化黑名单（checkAutoType）, 或者建议组件使用者完全把autoType 给关闭了，没办法一劳永逸地解决这个潜在的风险。

我们从中可以得到的一些启示，也是安全的一些常识：
1. 默认安全。 可以设置配置autoType 默认关闭，组件使用者真正需要支持反序列化时再打开
2. 白名单，而非黑名单。 仅允许反序列化特定的基本类型，其他的都不行，比如gson的设计

当然，一些安全设计本身也会让组件的使用受限，只能尽量求其平衡。

作为组件的使用者，我们在组件设计有问题且又不能用其他组件替换的情况下，也可以在调用面做一些防御，比如：
1. 不要反序列化不可信的数据
2. 给反序列化接口添加认证授权
3. 反序列化服务只允许监听在本地或者开启相应防火墙

提问来自yousa
答案来自张金发simba(腾讯大佬)

**Comment by rootsongjc** [comment]
长时间为提交，关闭 issue。
