### ISSUE TITLE
【翻译】翻译Kubernetes Operators

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/cloudnative.to#97]
简介：
kubernetes-operators：本书详细描述了Operator架构，讲授如何构建和部署Kubernetes Operator以及如何使用Go SDK，是一篇很不错的入门文档。简单翻了下，这本书有点简单，比较适合初学者
Programming Kubernetes：这本书我今天看了第一章，让我印象很深刻的一部分是，它简要又深刻地介绍了Controller和Operator的核心——事件机制：为什么基于边缘触发结合定期对账的机制是更合适的？
![image](https://user-images.githubusercontent.com/3816205/86262254-39894a80-bbf2-11ea-89ed-99c24d3b5a3a.png)

电子书下载：
[Programming.Kubernetes](https://github.com/cloudnativeto/cloudnative.to/files/4857064/Programming.Kubernetes.pdf)
[kubernetes-operators](https://github.com/cloudnativeto/cloudnative.to/files/4857067/kubernetes-operators.pdf)

讨论事项：
1、该电子书是否值得翻译
2、若值得翻译，征募志愿者

进展跟踪：
![image](https://user-images.githubusercontent.com/3816205/86319004-fbc60980-bc65-11ea-9aa4-5ae6fdb8a269.png)
https://www.processon.com/view/link/5efd6cd5e0b34d4dba64cbcc

**Comment by Miss-you** [comment]
简单翻了下，比较适合初学者

**Comment by Miss-you** [comment]
另外，再补充一篇文章，programming kubernetes

**Comment by gasxia** [comment]
申请志愿者参与翻译，另外 Programming Kubernetes 也可以参与翻译。这本书已经粗读过一遍，粗略翻译总结了前2章。

**Comment by zhaoweiguo** [comment]
申请参与，PS：prometheus相关的中文版更少

**Comment by rootsongjc** [comment]
关于云原生相关的开源软件、Kubernetes 编程、Operator 等可以选一个官网或者书籍，组织下社区翻译下。现在先征集下线索，大家讨论下。@Miss-you

**Comment by webup** [comment]
申请参与：PS：Programming Kubernetes 这书哪儿有电子版吗

**Comment by webup** [comment]
> 另外，再补充另一本书，programming kubernetes

这本书有电子版可以分享吗

**Comment by kevin-zhaoshuai** [comment]
申请参与，谢谢

**Comment by helight** [comment]
申请参与

**Comment by hzliangbin** [comment]
+1

**Comment by wenhuwang** [comment]
+1

**Comment by ericericlee** [comment]
operator的前言部分我基本已经完成了，今天开始第1章

**Comment by rootsongjc** [comment]
[Programming Kubernetes.pdf](https://github.com/cloudnativeto/cloudnative.to/files/4857064/Programming.Kubernetes.pdf)
[kubernetes-operators.pdf](https://github.com/cloudnativeto/cloudnative.to/files/4857067/kubernetes-operators.pdf)
这两本书都附在这里了，大家可以看下投个票吧，如果要翻译的话，希望一起翻译哪一本？然后社区一起组织下。
分别在不同的书名回复中点赞👍

**Comment by rootsongjc** [comment]
Kubernetes Operators

**Comment by rootsongjc** [comment]
Programming Kubernetes

**Comment by Miss-you** [comment]
Programming Kubernetes看起来内容更多些，个人但腾讯团队已经翻译过（没有开源），是不是优先翻译《Kubernetes Operators》比较好？否则翻译《Programming Kubernetes》会不会存在抄袭的嫌疑？

**Comment by rootsongjc** [comment]
既然腾讯没有开源出来，那就算不上抄袭吧，反正我们又都没看到🐶

**Comment by githubtest007** [comment]
Programming Kubernetes

**Comment by rootsongjc** [comment]
> Programming Kubernetes

请在这里点👍投票

![image](https://user-images.githubusercontent.com/3328185/86247045-8400cc00-bbde-11ea-822d-f1fb5d9ff9c9.png)

**Comment by lonng** [comment]
非常赞的想法，我们组织一下吧

**Comment by Miss-you** [comment]
> @Miss-you 非常赞的想法，这个涉及版权问题，我觉得可能需要先联系一下出版社，然后我们组织翻译，这个书内容比较少，翻译应该会比较快。

感谢提醒

**Comment by rootsongjc** [comment]
这两本书我可以问问电子工业出版社，看看有没有引进。

**Comment by brewHouses** [comment]
申请参与翻译 operator

**Comment by rootsongjc** [comment]
这两本书已经被国内的出版社引进了，但是还不清楚是否已经分配给人翻译，@Miss-you 会跟 O'Reilly 联系看看版权是分配给了国内哪家出版社。然后我们在问问对应的出版社看看是否已经有人在翻译的（估计是已经有了）。

**Comment by Miss-you** [comment]
hi，出版社我联系到了，oreilly将中文版版权卖给了中国电力出版社。据了解，这两本书出版社已经翻译完成，预计2021年出版。

**Comment by Miss-you** [comment]
不过另一方面，大家还有什么其他觉得不错的跟云原生相关的书么？也欢迎大家推荐

**Comment by Miss-you** [comment]
或者有没有比较好的仅仅社区内的人传阅且不侵权的办法呢？（我手里有一份已经基本翻译好的《programming kubernetes》）

**Comment by rootsongjc** [comment]
可以放到我们社区的 Google drive 里，仅限邀请才可以浏览，且禁止下载。
![image](https://user-images.githubusercontent.com/3328185/86511052-f4e6f480-be27-11ea-8789-b77e0862154c.png)
![image](https://user-images.githubusercontent.com/3328185/86511055-f7494e80-be27-11ea-8a67-49bb44b44699.png)

**Comment by Miss-you** [comment]
待解决的事情：
1、《programming kubernetes》中文版转载申请
2、将该内容放到google docs中

**Comment by Miss-you** [comment]
后续问题会在

**Comment by gasxia** [comment]
@rootsongjc 如何获得邀请？

**Comment by rootsongjc** [comment]
@gasxia 请关注这个 issue，https://github.com/cloudnativeto/community/issues/19

**Comment by hehua2018** [comment]
求分享中文版

**Comment by rootsongjc** [comment]
本书电子版已不支持下载，请大家购买正版中文翻译。
