### ISSUE TITLE
性能提升40%: 腾讯 TKE 用 eBPF绕过 conntrack 优化K8s Service | 云原生社区 

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/cloudnative.to#98]
Kubernetes Service[1] 用于实现集群中业务之间的互相调用和负载均衡，目前社区的实现主要有userspace，iptables和IPVS三种模式。IPVS模式的性能最好，但依然有优化的空间。该模式利用IPVS内核模块实现DNAT，利用nf_conntrack/iptables实现SNAT。nf_conntrack是为通用目的设计的，其内部的状态和流程都比较复杂，带来很大的性能损耗。

腾讯TKE团队[2] 开发了新的IPVS-BPF模式，完全绕过nf_conntrack的处理逻辑，使用eBPF完成SNAT功能。对最常用的Pod访问ClusterIP场景，短连接性能提升40%，p99时延降低31%；NodePort场景提升，详情见下表和性能测量章节。

https://mp.weixin.qq.com/s/VCIDNT_JR97SV0axsCUbgw

**Comment by rootsongjc** [comment]
公众号已发布，[文末赠书 | 性能提升40%: 腾讯 TKE 用 eBPF绕过 conntrack 优化K8s Service](https://mp.weixin.qq.com/s?__biz=MzI1NTE2NDE2MA==&mid=2649382056&idx=1&sn=3d374796b05cec790500a54c688989d5&chksm=f224d6c7c5535fd17d34c18bea34ea925e1c876d5aeb7ec092ae682fc64ab13122a5e31c6a29&scene=0&xtrack=1#rd)。

**Comment by rootsongjc** [comment]
已经过去快一个月了，是否可以提交了？

**Comment by rootsongjc** [comment]
时间太久了，没有转载的价值，关闭该 issue。
